### ISSUE TITLE
Generated html document displays (C) as Copyright symbol.

### ISSUE THREAD

**Issue by gemunulk** [getgauge/spectacle#14]
Test step to validate units Celsius (C) displays as Copyright symbol in html document.

E.g. 
* Validate table first "5" rows for matches 
|description           |regex_pattern|
|--------------------|---------------|
|Cheks for units(C)	   |(C)$	 	 |
|Cheks for units(F)    |(F)$	 	 |

**Comment by sguptatw** [comment]
Verified with
```
Gauge version: 1.0.1.nightly-2018-07-31
Commit Hash: 4ae7c9a

Plugins
-------
html-report (4.0.5.nightly-2018-07-25)
```
and works as expected.
