### ISSUE TITLE
provide support for round brackets in tag expressions as is in gauge

### ISSUE THREAD

**Issue by ab-yz** [getgauge/spectacle#15]
To be able to use spectacle as a tool for static tag analysis for gauge, I need to be able to execute the same tag expressions in spectacle as is possible in gauge.
In gauge, it is possible to have tag expressions with round brackets - this is not yet possible in spectacle.
Give spectacle the ability to work with tag expressions containing (possibly more than one set of) round brackets like in "(tagA | tagB) & !tagC".
Right now using () in spectacle gives: "No Specifications found that matches the given tag expression..."

**Comment by kashishm** [comment]
@ab-yz Please try this with the [latest spectacle nightly](https://bintray.com/gauge/spectacle/Nightly/_latestVersion) and let us know if you still face the same issue.

**Comment by ab-yz** [comment]
Everything is working fine, thank you very much!
