### ISSUE TITLE
some weird letters in generated docs in firefox

### ISSUE THREAD

**Issue by ab-yz** [getgauge/spectacle#16]
When generating docs from specs in UTF-8, it seems like the encoding information probably gets lost because some weird letters will show up in firefox, only tested in firefox 53 on mac.

Firefox opens the docs in "western", when manually changing this in firefox to "unicode", it will show the correct letters.

Then found here: http://stackoverflow.com/questions/29578122/why-there-is-no-utf-8-encoding-in-firefox
to add:
&lt;meta http-equiv="Content-Type" content="text/html; charset=utf-8"&gt;
to a generated spec html file also will cause firefox to show all letters correct.

Don't know if this is just the way firefox works (see comment in above link "Firefox defaults to latin1") or if it's an option to anyhow read the spec encoding and generate such a meta tag, too.

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.
