### ISSUE TITLE
Concepts are not getting converted

### ISSUE THREAD

**Issue by sguptatw** [getgauge/spectacle#2]
**Expected behavior**
The concepts should get converted too as part of the documentation. It should also list the number of concepts.

**Version**

```
Gauge version: 0.5.1.nightly-2016-06-16

Plugins
-------
html-report (2.1.1.nightly-2016-06-02)
java (0.4.1.nightly-2016-06-16)
m2h (0.0.1)
xml-report (0.1.2.nightly-2016-05-27)
```

**Comment by zabil** [comment]
Closing this as an old issue. However, any PR's to fix this will be merged.
