### ISSUE TITLE
Feature Request: support PlantUML

### ISSUE THREAD

**Issue by trung** [getgauge/spectacle#21]
It would be great to support diagrams using [PlantUML](https://plantuml.com).

Related: https://github.com/getgauge/html-report/issues/239

**Comment by nehashri** [comment]
@trung I am sure others may benefit from this, but I feel there are a lot of users who may not need this. Also, this would mean adding an external dependency to the existing spectacle plugin.

However, you can always create another plugin for Gauge with PlantUML. This will let you customise the spectacle document as per your needs.

You can always reach out to us to write your own custom plugin. You can also try forking the existing spectacle to help get started.
