### ISSUE TITLE
[Enhancement] Visualization of the flow

### ISSUE THREAD

**Issue by sguptatw** [getgauge/spectacle#9]
I want to be able to visualize the flow with a selected number of specifications
- The steps in the given set of specifications are the nodes.
- Two consecutive steps are connected with an edge with the arrow pointing towards the latter step.
- I want an ability to manually select the specifications from a given test suite.
- I want an ability to give a filter criteria to select the specifications to plot the information.

**Comment by zabil** [comment]
Closing this as Gauge will not be implementing this feature.
